QTwebdulich/QTwebdulich/Areas/Admin/Controllers/SharedController.cs
using System.Web.Mvc;

namespace QTwebdulich.Areas.Admin.Controllers
{
    public class SharedController : Controller
    {
        [ChildActionOnly]
        public ActionResult DemDonHangMoi()
        {
            return PartialView();
        }
    }
}

QTwebdulich/QTwebdulich/Controllers/CustomerController.cs
using QTwebdulich.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.Web.Mvc;
using QTwebdulich.Controllers;
using QTwebdulich.Areas.Admin.Controllers;
using System.Net;

namespace QTwebdulich.Controllers
{
    public class CustomerController : Controller
    {
        private webdulichEntities db = new webdulichEntities();
        public Helper Helper = new Helper();
        public ActionResult Index()
        {
            var session = Session["ClientUser"];
            if (session == null)
            {
                return Redirect("/");
            }

            khachhang sessionKhachhang = session as khachhang;
            return View(sessionKhachhang);
        }


        public ActionResult ChangePassword()
        {
            var session = Session["ClientUser"];
            if (session == null)
            {
                return Redirect("/");
            }

            khachhang sessionKhachhang = session as khachhang;
            return View(sessionKhachhang);
        }

        public class ClassPassword
        {
            public string password_cu { get; set; }
            public string password_moi { get; set; }
        }

        [HttpPost]
        public ActionResult ChangePassword(ClassPassword thongtinmatkhau)
        {
            try
            {
                var session = Session["ClientUser"];
                if (session == null)
                {
                    return Redirect("/");
                }

                khachhang sessionKhachhang = session as khachhang;

                khachhang khachhang = db.khachhangs.FirstOrDefault(x => x.id == sessionKhachhang.id);

                if (thongtinmatkhau.password_cu == thongtinmatkhau.password_moi)
                {
                    ViewBag.message = "Trùng mật khẩu cũ";
                    return View();
                }
                if (thongtinmatkhau.password_cu != khachhang.password)
                {
                    ViewBag.message = "Mật khẩu cũ không chính xác";
                    return View();
                }

                
                khachhang.ngaycapnhat = DateTime.Now;
                khachhang.password = thongtinmatkhau.password_moi;
                db.Entry(khachhang).State = EntityState.Modified;
                db.SaveChanges();
            }
            catch (Exception) { }

            return Redirect("~/Customer");
        }

        public ActionResult Order()
        {
            var session = Session["ClientUser"];
            if (session == null)
            {
                return Redirect("/");
            }

            khachhang sessionKhachhang = session as khachhang;
            var chitietdattours = db.chitietdattours
                .Include(c => c.tour)
                .Where(s => s.makhach == sessionKhachhang.id && s.daxoa != true)
                .OrderByDescending(x => x.ngaytao).ToList();
            return View(chitietdattours);
        }

        [HttpPost]
        public ActionResult Update(khachhang account)
        {
            try
            {
                var session = Session["ClientUser"];
                if (session == null)
                {
                    return Redirect("/");
                }

                khachhang sessionKhachhang = session as khachhang;


                khachhang khachhang = db.khachhangs.FirstOrDefault(x => x.id == sessionKhachhang.id);
                khachhang.ngaycapnhat = DateTime.Now;
                khachhang.ten = account.ten;
                khachhang.dienthoai = account.dienthoai;
                db.Entry(khachhang).State = EntityState.Modified;
                db.SaveChanges();
            }
            catch (Exception) {}
            
            return Redirect("~/Customer");
        }

        public ActionResult Cancel(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var session = Session["ClientUser"];
            if (session == null)
            {
                return Redirect("/");
            }

            var foundOrder = db.chitietdattours.FirstOrDefault(x=>x.id == id);
            var tinhtrangmoi = Convert.ToInt32(AdminCommon.TinhTrangDon.Moi);
            if (foundOrder != null && foundOrder.tinhtrangdonhang == tinhtrangmoi)
            {
                // Huy don
                foundOrder.tinhtrangdonhang = Convert.ToInt32(AdminCommon.TinhTrangDon.DaHuy);
                foundOrder.ngaycapnhat = DateTime.Now;
                db.Entry(foundOrder).State = EntityState.Modified;
                db.SaveChanges();
            }
            return Redirect("~/Customer/Order");
        }


        public ActionResult Login()
        {
            var session = Session["ClientUser"];
            if (session != null)
            {
                return Redirect("/");
            }

            return View();
        }

        [HttpPost]
        public ActionResult Login(khachhang account)
        {
            khachhang u = db.khachhangs
                .Where(m => m.username == account.username 
                    && m.password == account.password 
                    && m.daxoa != true 
                    && m.active == true)
                .FirstOrDefault();
            if (u != null)
            {
                Session["ClientUser"] = u;
                Session["ClientUserName"] = u.ten;

                return Redirect("/");
            }
            else
            {
                Session["ClientUser"] = null;
                ViewBag.Message = "";
                ViewBag.Message = "Sai tài khoản hoặc mật khẩu";
                return View();
            }
        }

        public ActionResult Register()
        {
            var session = Session["ClientUser"];
            if (session != null)
            {
                return Redirect("~/");
            }

            return View();
        }

        [HttpPost]
        public ActionResult Register([Bind(Include = "ten,dienthoai,email,username,password")] khachhang account)
        {
            try
            {
                var foundUserName = db.khachhangs.Where(s => s.username == account.username).ToList();
                if(foundUserName.Count > 0)
                {
                    ViewBag.foundUserName = "Trùng tên đăng nhập";
                    return View();
                }

                var foundEmail = db.khachhangs.Where(s => s.email == account.email).ToList();
                if (foundEmail.Count > 0)
                {
                    ViewBag.foundEmail = "Trùng email";
                    return View();
                }

                var foundSdt = db.khachhangs.Where(s => s.dienthoai == account.dienthoai).ToList();
                if (foundSdt.Count > 0)
                {
                    ViewBag.foundSdt = "Trùng số điện thoại";
                    return View();
                }


                var khachhang = new khachhang();
                khachhang.ten = account.ten;
                khachhang.dienthoai = account.dienthoai;
                khachhang.email = account.email;
                khachhang.username = account.username;
                khachhang.password = account.password;
                khachhang.active = true;
                khachhang.daxoa = false;
                khachhang.ngaytao = DateTime.Now;
                khachhang.ngaycapnhat = DateTime.Now;
                db.khachhangs.Add(khachhang);
                db.SaveChanges();

                Session["ClientUser"] = khachhang;
                Session["ClientUserName"] = khachhang.ten;
                return Redirect("/");
            }
            catch (Exception ex)
            {
                return View();
            }
            
        }

        public ActionResult Logout()
        {
            Session["ClientUser"] = null;
            Session["ClientUserName"] = null;
            return Redirect("~/");
        }
    }
}

QTwebdulich/QTwebdulich/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QTwebdulich.Controllers
{
    public class SharedController : Controller
    {
        [ChildActionOnly]
        public ActionResult SearchForm()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult SearchForm(string tentour)
        {
            string urlRedirect = "~/Tours/Search?tour=" + tentour;
            return Redirect(urlRedirect);
        }
    }
}

QTwebdulich/QTwebdulich/Controllers/ToursController.cs
using QTwebdulich.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.Web.Mvc;
using System.Net;
using QTwebdulich.Controllers;
using System.Text.RegularExpressions;
using System.Globalization;

namespace QTwebdulich.Controllers
{
    public class ToursController : Controller
    {
        // GET: Tours
        private webdulichEntities db = new webdulichEntities();
        public Helper Helper = new Helper();
        public ActionResult Index()
        {

            // Loại = 3: Tour
            banner banner = db.banners.FirstOrDefault(x => x.loai == 3 && x.active == true && x.daxoa == false);
            ViewBag.banner = "";
            if (banner != null)
            {
                ViewBag.banner = banner.hinhanh;
            }
            // lay list những tour nổi bật = true, đã xóa = false
            List<tour> toursNoiBat = db.tours
                    .Include(t => t.diadiem)
                    .Include(t => t.phuongtien)
                    .Include(t => t.taikhoan)
                    .Where(x => x.noibat == true && x.daxoa == false && x.hienthi == true).ToList();
            ViewBag.tourNoiBat = toursNoiBat;

            List<tour> toursThuong = db.tours
                    .Include(t => t.diadiem)
                    .Include(t => t.phuongtien)
                    .Include(t => t.taikhoan)
                    .Where(x => x.daxoa == false && x.hienthi == true).ToList();
            ViewBag.toursThuong = toursThuong;
            return View();
        }

        public ActionResult Detail(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tour tour = db.tours.FirstOrDefault(x => x.id == id && x.daxoa != true);
            if(tour == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            };
            ViewBag.tour = tour;
            // Loại = 4: Chi tiết tour
            banner banner = db.banners.FirstOrDefault(x => x.loai == 4 && x.active == true && x.daxoa == false);
            ViewBag.banner = "";
            if (banner != null)
            {
                ViewBag.banner = banner.hinhanh;
            }

            //list tour noi bat sidebar
            List<tour> toursNoiBat = db.tours
                    .Include(t => t.diadiem)
                    .Include(t => t.phuongtien)
                    .Include(t => t.taikhoan)
                    .Where(x => x.noibat == true && x.daxoa == false && x.hienthi == true)
                    .Take(6)
                    .ToList();
            ViewBag.tourNoiBat = toursNoiBat;


            return View(tour);
        }

        // http://dotnet.edu.vn/ChuyenMuc/Ham-chuyen-doi-chuoi-ky-tu-co-dau-thanh-khong-dau-CNet-184.aspx
        public static string ConvertToUnSign(string text)
        {
            for (int i = 33; i < 48; i++)
            {
                text = text.Replace(((char)i).ToString(), "");
            }

            for (int i = 58; i < 65; i++)
            {
                text = text.Replace(((char)i).ToString(), "");
            }

            for (int i = 91; i < 97; i++)
            {
                text = text.Replace(((char)i).ToString(), "");
            }
            for (int i = 123; i < 127; i++)
            {
                text = text.Replace(((char)i).ToString(), "");
            }
            text = text.Replace(" ", "-");
            Regex regex = new Regex(@"\p{IsCombiningDiacriticalMarks}+");
            string strFormD = text.Normalize(System.Text.NormalizationForm.FormD);
            string result = regex.Replace(strFormD, String.Empty).Replace('\u0111', 'd').Replace('\u0110', 'D');
            result = result.Replace("-", " ");
            return result;
        }

        public ActionResult Search(string tour)
        {
            // Creates a TextInfo based on the "en-US" culture.
            TextInfo myTI = new CultureInfo("en-US", false).TextInfo;

            string tenUppercase_title = myTI.ToTitleCase(tour); // đà lạt -> Đà Lạt
            string tenUppercase = tour.ToUpper(); // đà lạt -> ĐÀ LẠT
            string tenLowercase = tour.ToLower(); // Đà LạT -> đà lạt

            string tenKhongDau = ConvertToUnSign(tour);
            string tenKhongDau_uppercase = tenKhongDau.ToUpper();
            string tenKhongDau_lowercase = tenKhongDau.ToLower();
            string tenKhongDau_title = myTI.ToTitleCase(tenKhongDau); // da Lat -> Da Lat

            banner banner = db.banners.FirstOrDefault(x => x.loai == 3 && x.active == true && x.daxoa == false);
            ViewBag.banner = "";
            if (banner != null)
            {
                ViewBag.banner = banner.hinhanh;
            }
            
            List<tour> toursThuong = db.tours
                    .Include(t => t.diadiem)
                    .Include(t => t.phuongtien)
                    .Include(t => t.taikhoan)
                    .Where(
                        x => x.daxoa == false 
                        && x.hienthi == true 
                        && 
                        (
                            x.ten.Contains(tour) 
                            || x.ten.Contains(tenKhongDau)
                            || x.ten.Contains(tenUppercase_title) 
                            || x.ten.Contains(tenUppercase) 
                            || x.ten.Contains(tenLowercase) 
                            || x.ten.Contains(tenKhongDau_uppercase) 
                            || x.ten.Contains(tenKhongDau_lowercase) 
                            || x.ten.Contains(tenKhongDau_title)
                        )
                    )
                    .ToList();
            ViewBag.toursThuong = toursThuong;
            return View();
        }
    }
}

QTwebdulich/QTwebdulich/Views/Shared/SearchForm.cshtml
@using (Html.BeginForm("SearchForm", "Shared"))
{
    <div id="search_form">
        <form action="#" method="get" style="position: absolute; padding: 15px">
            <div id="search-locations">
                <h3 style="color: white"> Bạn muốn đi du lịch ở đâu ?</h3>
                <input class="form-control biginput" name="tentour" id="autocomplete" type="search"
                       required placeholder=""
                       style="height:45px;width: 139%; font-size: 18px;">
            </div>
            <script>
                /* Placeholder Typewriter */
                var placeholderText = [
                    "Bãi Biển Nha Trang ?",
                    "Đảo Hòn Tằm ?",
                    "Vinpearl Land ?",
                    "Đảo Hòn Mun ?",
                    "Vịnh Ninh Vân ?",
                    "Vịnh Vân Phong?",
                    "Bãi Biển Đại Lãnh?",
                    "Chợ Đầm Nha Trang?"
                ];
                $('#autocomplete').placeholderTypewriter({ text: placeholderText });
            </script>
            <div style="margin: auto; text-align: center">
                <button type="submit" class="btn mybtn-style1" id="booking_form_search"
                        style="background: #2196f3">
                    TÌM KIẾM
                </button>
            </div>
        </form>
    </div>
}

QTwebdulich/QTwebdulich/Views/Shared/_Footer.cshtml
<footer style="margin-top: -20px">

    <div class="container">

        <div class="row ">
            <div class="col-md-3 col-sm-3 col-xs-12">
                <div class="footer-content">
                    <h4> Dịch Vụ</h4>
                    <hr>

                    <span> Tour trong nước</span> <br>
                    <span> Vé Máy Bay</span> <br>
                    <span> Thuê Xe</span> <br>

                </div>

            </div>
            <div class="col-md-3 col-sm-3 col-xs-12">
                <div class="footer-content">
                    <h4> Thông Tin</h4>
                    <hr>

                    <span> Tuyến Điểm</span><br>
                    <span> Tin Tức</span><br>
                    <span> Cẩm nang Du Lịch</span><br>
                    <span> Tin Du Lịch</span>


                </div>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12">
                <div class="footer-content">
                    <h4> Chăm sóc khách hàng</h4>
                    <hr>
                    <span> Phiếu Góp Ý</span><br>
                    <span> Ý Kiến Khách Hàng</span><br>
                    <span> Hướng Dẫn Thanh Toán</span><br>
                    <span> Điều Khoản Chung</span>


                </div>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12">
                <div class="footer-content">
                    <h4> Liên Hệ</h4>
                    <hr>
                    <span> Giới Thiệu QuangTungTour</span><br>
                    <span> Phone: 0985708579</span><br>
                    <span> Mail:tranquangtung9889@gmail.com</span><br>
                    <span> Địa Chỉ : 236B Đường Lê Văn Sỹ, Phường 1, Tân Bình, Hồ Chí Minh</span>


                </div>
            </div>

        </div>
    </div>


</footer>

<footer class="container-fluid text-center " style="padding: 10px">
    <a href="#myPage" title="To Top">
        <span class="fa fa-arrow-circle-up fa-2x  faa-bounce animated-hover " style="color: black;"></span>
    </a>
    <p>Trần Quang Tùng 04_CNTT_03</p>
</footer>

QTwebdulich/QTwebdulich/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>QuangTungTour</title>

    <!--css-->
    <link rel="stylesheet" href="http://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
    <link type="text/css" rel="stylesheet" href="~/Assets/css/index.css" />
    <link rel="stylesheet" href="~/Assets/css/danhgia.css">
    <link rel="stylesheet" href="~/Assets/css/signup.css">
    <link rel="stylesheet" href="~/Assets/css/custom.css">
    
    
    <link rel="stylesheet" href="~/Assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Assets/fontawesome/css/fontawesome.min.css">
    <link rel="stylesheet" href="~/Assets/fontawesome/fontawesome-amination.css">
    <link rel="stylesheet" href="~/Assets/bootstrap/bootstrap.min.css">
    <link rel="stylesheet" href="~/Assets/css/lienhe.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <script src="~/Assets/jquery/jquery-3.3.1.min.js"></script>
    <script src="~/Assets/jquery/hieuung.js"></script>
    <script src="~/Assets/jquery/placeholderTypewriter.js"></script>
    <script src="~/Assets/js/login.js"></script>
    <script src="~/Assets/js/bootstrap.min.js"></script>
    <script src="~/Assets/js/index.js"></script>
    <script type="text/javascript" src="http://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
</head>
<body id="myPage">
    @RenderBody()
</body>
</html>

QTwebdulich/QTwebdulich/Views/Shared/_Menu.cshtml
<nav>
    <div class="container-fluid">


        <div id="left-nav">
            <ul style="list-style-type: none">
                <li class="left-nav-city">
                    <a href="/" class="txt-name-location menu-label">  
                        <span class="txt-name-location">HOME </span>
                    </a>
                </li>
                <li class="left-nav-city">
                    <a href="@Url.Action("Index", "Tours")" class="txt-name-location menu-label">
                        <span class="txt-name-location">TOUR </span>
                    </a>
              
                </li>
                <li class="left-nav-city">
                    <a href="@Url.Action("Contact", "Home")" id="lh"> 
                     <span class="txt-name-location menu-label">LIÊN HỆ </span></a>
                </li>
                @{
                    var session_user = Session["ClientUser"];
                    if (session_user != null)
                    {
                        <li class="left-nav-city">
                            <a href="~/Customer">
                                <span class="txt-name-location menu-label">THÔNG TIN CÁ NHÂN </span>
                            </a>
                        </li>
                        <li class="left-nav-city">
                            <a href="@Url.Action("Logout", "Customer")">
                                <span class="txt-name-location menu-label">ĐĂNG XUẤT</span>
                            </a>
                        </li>
                        <li style="float:left">
                            <span class="block-hello-user">Xin chào, @Session["ClientUserName"]</span>
                        </li>
                    }
                    else
                    {
                        <li class="left-nav-city">
                            <a href="@Url.Action("Login", "Customer")">
                                <span class="txt-name-location menu-label">ĐĂNG NHẬP</span>
                            </a>
                        </li>
                    }
                }
                
            </ul>
        </div>
    </div>
</nav>