QTwebdulich/QTwebdulich/Areas/Admin/Controllers/LienHeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QTwebdulich.Models;

namespace QTwebdulich.Areas.Admin.Controllers
{
    public class LienHeController : Controller
    {
        private webdulichEntities db = new webdulichEntities();

        // GET: Admin/LienHe
        public ActionResult Index()
        {
            return View(db.lienhes.ToList());
        }

        // GET: Admin/LienHe/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            lienhe lienhe = db.lienhes.Find(id);
            if (lienhe == null)
            {
                return HttpNotFound();
            }
            return View(lienhe);
        }

        // GET: Admin/LienHe/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/LienHe/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,hoten,diachi,email,phone,tieude,yeucau,ngaytao")] lienhe lienhe)
        {
            if (ModelState.IsValid)
            {
                db.lienhes.Add(lienhe);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(lienhe);
        }

        // GET: Admin/LienHe/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            lienhe lienhe = db.lienhes.Find(id);
            if (lienhe == null)
            {
                return HttpNotFound();
            }
            return View(lienhe);
        }

        // POST: Admin/LienHe/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,hoten,diachi,email,phone,tieude,yeucau,ngaytao")] lienhe lienhe)
        {
            if (ModelState.IsValid)
            {
                db.Entry(lienhe).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(lienhe);
        }

        // GET: Admin/LienHe/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            lienhe lienhe = db.lienhes.Find(id);
            if (lienhe == null)
            {
                return HttpNotFound();
            }
            return View(lienhe);
        }

        // POST: Admin/LienHe/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            lienhe lienhe = db.lienhes.Find(id);
            db.lienhes.Remove(lienhe);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QTwebdulich/QTwebdulich/Areas/Admin/Controllers/SharedController.cs
using System.Web.Mvc;

namespace QTwebdulich.Areas.Admin.Controllers
{
    public class SharedController : Controller
    {
        [ChildActionOnly]
        public ActionResult DemDonHangMoi()
        {
            return PartialView();
        }
    }
}

QTwebdulich/QTwebdulich/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QTwebdulich.Controllers
{
    public class SharedController : Controller
    {
        [ChildActionOnly]
        public ActionResult SearchForm()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult SearchForm(string tentour)
        {
            string urlRedirect = "~/Tours/Search?tour=" + tentour;
            return Redirect(urlRedirect);
        }
    }
}

QTwebdulich/QTwebdulich/Controllers/ToursController.cs
using QTwebdulich.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.Web.Mvc;
using System.Net;
using QTwebdulich.Controllers;
using System.Text.RegularExpressions;
using System.Globalization;

namespace QTwebdulich.Controllers
{
    public class ToursController : Controller
    {
        // GET: Tours
        private webdulichEntities db = new webdulichEntities();
        public Helper Helper = new Helper();
        public ActionResult Index()
        {

            // Loại = 3: Tour
            banner banner = db.banners.FirstOrDefault(x => x.loai == 3 && x.active == true && x.daxoa == false);
            ViewBag.banner = "";
            if (banner != null)
            {
                ViewBag.banner = banner.hinhanh;
            }
            // lay list những tour nổi bật = true, đã xóa = false
            List<tour> toursNoiBat = db.tours
                    .Include(t => t.diadiem)
                    .Include(t => t.phuongtien)
                    .Include(t => t.taikhoan)
                    .Where(x => x.noibat == true && x.daxoa == false && x.hienthi == true).ToList();
            ViewBag.tourNoiBat = toursNoiBat;

            List<tour> toursThuong = db.tours
                    .Include(t => t.diadiem)
                    .Include(t => t.phuongtien)
                    .Include(t => t.taikhoan)
                    .Where(x => x.daxoa == false && x.hienthi == true).ToList();
            ViewBag.toursThuong = toursThuong;
            return View();
        }

        public ActionResult Detail(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tour tour = db.tours.FirstOrDefault(x => x.id == id && x.daxoa != true);
            if(tour == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            };
            ViewBag.tour = tour;
            // Loại = 4: Chi tiết tour
            banner banner = db.banners.FirstOrDefault(x => x.loai == 4 && x.active == true && x.daxoa == false);
            ViewBag.banner = "";
            if (banner != null)
            {
                ViewBag.banner = banner.hinhanh;
            }

            //list tour noi bat sidebar
            List<tour> toursNoiBat = db.tours
                    .Include(t => t.diadiem)
                    .Include(t => t.phuongtien)
                    .Include(t => t.taikhoan)
                    .Where(x => x.noibat == true && x.daxoa == false && x.hienthi == true)
                    .Take(6)
                    .ToList();
            ViewBag.tourNoiBat = toursNoiBat;


            return View(tour);
        }

        // http://dotnet.edu.vn/ChuyenMuc/Ham-chuyen-doi-chuoi-ky-tu-co-dau-thanh-khong-dau-CNet-184.aspx
        public static string ConvertToUnSign(string text)
        {
            for (int i = 33; i < 48; i++)
            {
                text = text.Replace(((char)i).ToString(), "");
            }

            for (int i = 58; i < 65; i++)
            {
                text = text.Replace(((char)i).ToString(), "");
            }

            for (int i = 91; i < 97; i++)
            {
                text = text.Replace(((char)i).ToString(), "");
            }
            for (int i = 123; i < 127; i++)
            {
                text = text.Replace(((char)i).ToString(), "");
            }
            text = text.Replace(" ", "-");
            Regex regex = new Regex(@"\p{IsCombiningDiacriticalMarks}+");
            string strFormD = text.Normalize(System.Text.NormalizationForm.FormD);
            string result = regex.Replace(strFormD, String.Empty).Replace('\u0111', 'd').Replace('\u0110', 'D');
            result = result.Replace("-", " ");
            return result;
        }

        public ActionResult Search(string tour)
        {
            // Creates a TextInfo based on the "en-US" culture.
            TextInfo myTI = new CultureInfo("en-US", false).TextInfo;

            string tenUppercase_title = myTI.ToTitleCase(tour); // đà lạt -> Đà Lạt
            string tenUppercase = tour.ToUpper(); // đà lạt -> ĐÀ LẠT
            string tenLowercase = tour.ToLower(); // Đà LạT -> đà lạt

            string tenKhongDau = ConvertToUnSign(tour);
            string tenKhongDau_uppercase = tenKhongDau.ToUpper();
            string tenKhongDau_lowercase = tenKhongDau.ToLower();
            string tenKhongDau_title = myTI.ToTitleCase(tenKhongDau); // da Lat -> Da Lat

            banner banner = db.banners.FirstOrDefault(x => x.loai == 3 && x.active == true && x.daxoa == false);
            ViewBag.banner = "";
            if (banner != null)
            {
                ViewBag.banner = banner.hinhanh;
            }
            
            List<tour> toursThuong = db.tours
                    .Include(t => t.diadiem)
                    .Include(t => t.phuongtien)
                    .Include(t => t.taikhoan)
                    .Where(
                        x => x.daxoa == false 
                        && x.hienthi == true 
                        && 
                        (
                            x.ten.Contains(tour) 
                            || x.ten.Contains(tenKhongDau)
                            || x.ten.Contains(tenUppercase_title) 
                            || x.ten.Contains(tenUppercase) 
                            || x.ten.Contains(tenLowercase) 
                            || x.ten.Contains(tenKhongDau_uppercase) 
                            || x.ten.Contains(tenKhongDau_lowercase) 
                            || x.ten.Contains(tenKhongDau_title)
                        )
                    )
                    .ToList();
            ViewBag.toursThuong = toursThuong;
            return View();
        }
    }
}

QTwebdulich/QTwebdulich/Areas/Admin/Views/Shared/DemDonHangMoi.cshtml
<a href="@Url.Action("Index", "ChiTietDatTours" ,new { Area = "Admin" })">
    Danh sách đơn hàng 
    @{
        if (Session["demdonhangmoi"] != null)
        {
            <span id="don-hang-moi">(Mới @Session["demdonhangmoi"])</span>
        }
    }
</a>

QTwebdulich/QTwebdulich/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Admin System</title>
    <!-- Bootstrap Core CSS -->
    <link href="~/Areas/Admin/Assets/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="~/Areas/Admin/Assets/css/sb-admin.css" rel="stylesheet">
    <!-- Morris Charts CSS -->
    <link href="~/Areas/Admin/Assets/css/plugins/morris.css" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="~/Areas/Admin/Assets/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <script src="~/Areas/Admin/Assets/js/jquery.js"></script>
    <!-- jQuery -->
    <!-- Reference either Knockout or AngularJS, if you do -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/knockout/3.4.0/knockout-min.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.7.2/angular.min.js"></script>

    <!-- DevExtreme themes -->
    <link rel="stylesheet" type="text/css" href="https://cdn3.devexpress.com/jslib/18.2.8/css/dx.common.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn3.devexpress.com/jslib/18.2.8/css/dx.light.css" />

    <!-- DevExtreme library -->
    <script type="text/javascript" src="https://cdn3.devexpress.com/jslib/18.2.8/js/dx.all.js"></script>
    <link rel="stylesheet" href="http://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
    <script type="text/javascript" src="http://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>

    <link href="~/Areas/Admin/Assets/css/adminStyle.css" rel="stylesheet">
</head>
<body>
    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">Admin System</a>
            </div>
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">
                <li class="dropdown hidden">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-envelope"></i> <b class="caret"></b></a>
                    <ul class="dropdown-menu message-dropdown">
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="http://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading">
                                            <strong>John Smith</strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                        <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="http://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading">
                                            <strong>John Smith</strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                        <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="http://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading">
                                            <strong>John Smith</strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                        <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="message-footer">
                            <a href="#">Read All New Messages</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown hidden">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i> <b class="caret"></b></a>
                    <ul class="dropdown-menu alert-dropdown">
                        <li>
                            <a href="#">Alert Name <span class="label label-default">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-primary">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-success">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-info">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-warning">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-danger">Alert Badge</span></a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">View All</a>
                        </li>
                    </ul>
                </li>
            </ul>
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li>
                        <a href="@Url.Action("Index", "Report",new { Area = "Admin"})">Thống kê</a>
                    </li>
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#groupbanner">Quản lý Banner <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="groupbanner" class="collapse">
                            <li>
                                <a href="@Url.Action("Index", "Banners" ,new { Area = "Admin", loai = 1 })">Trang Chủ</a>
                            </li>
                            <li id="ad_hanhtrinh">
                                <a href="@Url.Action("Index", "Banners" ,new { Area = "Admin", loai = 2 })">Liên hệ</a>
                            </li>
                            <li id="ad_hanhtrinh">
                                <a href="@Url.Action("Index", "Banners" ,new { Area = "Admin", loai = 3 })">Tour</a>
                            </li>
                            <li id="ad_hanhtrinh">
                                <a href="@Url.Action("Index", "Banners" ,new { Area = "Admin", loai = 4 })">Chi tiết tour</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#grouptaikhoan">Quản lý tài khoản <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="grouptaikhoan" class="collapse">
                            <li>
                                <a href="@Url.Action("Index", "TaiKhoans" ,new { Area = "Admin" })">Admin </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "KhachHangs" ,new { Area = "Admin" })">Khách hàng</a>
                            </li>
                        </ul>
                    </li>
                  
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#groupsanpham">Quản lý Tour <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="groupsanpham" class="collapse">
                            <li>
                                <a href="@Url.Action("Index", "DiaDiems" ,new { Area = "Admin" })">Địa điểm</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "Tours" ,new { Area = "Admin" })">Tour</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#groupquanlidonhang">Quản lý đơn hàng 
                            <i class="fa fa-fw fa-caret-down"></i>
                            @{
                                if (Session["demdonhangmoi"] != null)
                                {
                                    <span id="don-hang-moi">(Mới @Session["demdonhangmoi"])</span>
                                }
                            }
                        </a>
                        <ul id="groupquanlidonhang" class="collapse">
                            <li class="block-danh-sach-don-hang">
                                @Html.Partial("DemDonHangMoi")
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "ChiTietDatTours" ,new { tinhtrangdon = 4, Area = "Admin" })">Danh sách đơn hàng đã hủy</a>
                            </li>
                        </ul>
                    </li>

                    <li>
                        <a href="@Url.Action("Index", "LienHe",new { Area = "Admin"})">Quản lý yêu cầu liên hệ</a>
                    </li>

                    <li>
                        <a href="@Url.Action("Logout", "Account",new { Area = "Admin"})">Thoát</a>
                    </li>
                </ul>
            </div>
        </nav>
        <div id="page-wrapper">
            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>
    </div>
    <!-- Bootstrap Core JavaScript -->
    <script src="~/Areas/Admin/Assets/js/bootstrap.min.js"></script>
    <!-- Morris Charts JavaScript -->
    <script src="~/Areas/Admin/Assets/js/plugins/morris/raphael.min.js"></script>
    <script src="~/Areas/Admin/Assets/js/plugins/morris/morris.min.js"></script>
    <script src="~/Areas/Admin/Assets/js/plugins/morris/morris-data.js"></script>
</body>
</html>